output: "../../config/output_files.json"

reference:
  design_bed: "reference/homo_sapiens.wgs.bed"
  design_intervals: "reference/wgs.interval_list" #HSMetrics
  design_intervals_gatk_cnv: "reference/wgs.interval_list"
  fasta: "reference/reference.fasta"
  fai: "reference/reference.fasta.fai"
  fasta_rna: "reference/reference.fasta"
  genome_dir: "reference"
  sites: "reference/sites.vcf.gz"
  wgs_intervals: "reference/wgs.interval_list"

annotate_cnv:
  cna_exons: "reference/hg38_CNA.bed" 

arriba:
  assembly: "reference/assembly.fasta"
  blacklist: "reference/arriba_blacklist.txt"
  extra: "-p abc.gff3 -k abc.tsv.gz"
  gtf: "reference/assembly.gtf"

arriba_draw_fusion:
  cytobands: "reference/cytobands.tsv"
  gtf: "reference/assembly.gtf"
  protein_domains: "reference/proteindomain.gff3"

bcftools_SNV:
  all: "reference/all.bed"
  aml: "reference/aml.bed"

bcftools_SV:
  all: "reference/all.bed"
  aml: "reference/aml.bed"

cnvkit_batch:
  normal_reference: "reference/cnvkit.cnn"

cnvkit_table:
  bedfile: "reference/cna_genes.bed"
  cyto_coordinates: "reference/cyto_coordinates.txt"
  # log_thresholds: "-0.19,0.2"
  # ploidy: "3"

cnv_html_report:
  show_table: true
  template_dir: "../../config/cnv_report_template"
  cnv_vcf:
    - annotation: cna_exons
      filter: cnv_hardfilter

crumble:

filter_vcf:
  germline: "../../config/config_germline_filter.yaml"
  cnv_hardfilter: "/../../config_cnv_hardfilter.yaml"

fusioncatcher:
  genome_path: "reference"

gatk_cnv_collect_allelic_counts:
  SNP_interval: "reference/wgs.interval_list"

gatk_cnv_denoise_read_counts_by_sex:
  pon_female: "reference/female.hdf5"
  pon_male: "reference/male.hdf5"

mosdepth_bed:
  design_bed: "reference/exome.bed"

multiqc:
  reports:
    DNA:
      config: "../../config/multiqc_dna_config.yaml"
    RNA:
      config: "../../config/multiqc_rna_config.yaml"

peddy:
  config: "peddy_mqc.tsv" 

pindel_call:
  include_bed: "reference/pindel.bed"

rseqc_gene_body_coverage:
  bed: "reference/gene_model.bed"

rseqc_inner_distance:
  bed: "reference/gene_model.bed"

sample_order_multiqc:
  sample_sheet: "SampleSheet.csv"

simple_sv_annotation:
  panel: "reference/panel.txt"
  fusion_pairs: "reference/fusion_pairs.txt"

snpeff:
  db: "SnpEff/GRCh38.99"

sortmerna:
  fasta:
    - "reference/id.fasta"
  index: "reference/"

star:
  genome_index: "reference/"

star_fusion:
  genome_path: "reference/"

svdb_merge:
  tc_method:
    - name: pathology
      cnv_caller:
        - cnvkit
        - gatk

vep:
  vep_cache: "reference/vep"
